const actionTypes = {
  LOGIN: 'LOGIN',
  IS_LOADING: 'IS_LOADING',
  IS_ERROR: 'IS_ERROR',
  IS_SUCCESS: 'IS_SUCCESS',
  SET_ROLE: 'SET_ROLE',
  LOGIN: 'LOGIN',
  SET_PAGE_TITLE: 'SET_PAGE_TITLE',
  ADD_CLASS: 'ADD_CLASS',
  BULK_ADD_CLASS: 'BULK_ADD_CLASS',
  ALL_CLASS: 'ALL_CLASS',
  EDIT_CLASS: 'EDIT_CLASS',
};

export default actionTypes;
